### ISSUE TITLE
Add key to set protoc version explicitly 

### ISSUE THREAD

**Issue by ThatScalaGuy** [higherkindness/sbt-mu-srcgen#237]
Currently, the protoc version is set by `skeuomorph`. `skeuomorph` was adopted to set the version explicitly to have the chance to use a build that runs on Apple Silcon. `sbt-mu-srcgen` should also provide a way to set the version explicitly in the build.sbt

**Comment by ThatScalaGuy** [comment]
created a small PR, feel free to use it.

**Comment by fedefernandez** [comment]
Thank you. I'll take care of it (need to make some changes on mu-scala first in order to have everything synchronized)
