### ISSUE TITLE
protoc-gen-validate / scalapb-validate plugin

### ISSUE THREAD

**Issue by chaddaksha** [higherkindness/sbt-mu-srcgen#303]
Hi, is it possible to use the scalapb-validate plugin in combination with this generator?

**Comment by chaddaksha** [comment]
Looks like I was able to find a workaround by updating the `Compile / PB.targets` defined:

```scala
lazy val muPbTargets = Compile / PB.targets
lazy val protocol = (project in file("protocol"))
  .settings(
    name := "protocol",
    // Needed for the generated code to compile
    libraryDependencies ++= List.concat(Dependencies.Refined, Dependencies.ProtobufGen),
    muSrcGenIdlType := IdlType.Proto,
    // Make it easy for 3rd-party clients to communicate with us via gRPC
    muSrcGenIdiomaticEndpoints := true,
    // Default value is src/main/resources
    muSrcGenSourceDirs := List(file("protocol/service")),
    // Generated protobufs contain lots of unused imports
    scalacOptions -= "-Wunused:imports"
  )
  .enablePlugins(SrcGenPlugin)
  .settings(
    Compile / PB.targets :=
      List.concat(
        // Preprocessor must be executed first
        List(scalapb.validate.preprocessor() -> (Compile / sourceManaged).value),
        muPbTargets.value,
        // Scalapb-validate must be executed afterwards
        List(scalapb.validate.gen()          -> (Compile / sourceManaged).value)
      )
  )
```

Not sure if there might be a more idiomatic way.

**Comment by fedefernandez** [comment]
@chaddaksha I've merged and published a snapshot version with this feature. Would you be able to verify if it works as expected?

Steps:
1. Add the sonatype snapshot repository to your plugins.sbt
2. Change the plugin version to `0.29.0+23-178b0143-SNAPSHOT`
3. Enable the validation with the setting key: `muSrcGenValidateProto:=true`

Thanks

**Comment by chaddaksha** [comment]
Thank you!

This seems to work. Only thing is I need to add the following myself to resolve `import "validate/validate.proto"`. I am surprised, since I see this dependency in the merged PR, but I am not sure if I am doing something wrong.
```
"com.thesamet.scalapb" %% "scalapb-validate-core" % "0.3.2" % "protobuf"
```

**Comment by fedefernandez** [comment]
@chaddaksha, thanks for checking it. I guess the dependency it's not carried transitively. I'll investigate a bit further.

**Comment by fedefernandez** [comment]
@chaddaksha I know what's happening. The dependency is on the scripted test. Plugin dependencies are not carried to the project, so users need to update their builds to include the dependency with `scalapb-validate-core`. Thanks for pointing this out, I'll update the docs in `mu-scala`.

**Comment by chaddaksha** [comment]
Sounds good - thank you!

**Comment by fedefernandez** [comment]
@chaddaksha it took more time than expected, but this is done in `0.29.1`. Thanks for your submission
