### ISSUE TITLE
Make it a manual plugin

### ISSUE THREAD

**Issue by cb372** [higherkindness/sbt-mu-srcgen#38]
Currently sbt-mu-srcgen is automatically enabled on all projects. But it prints an annoying message when it runs on projects where it has not been configured properly.

It would make more sense to ask users to enable it manually where it's needed, using `.enablePlugins(SrcGenPlugin)`.

**Comment by dmarticus** [comment]
Chatted with Chris about this and I'm going to take this cc @rafaparadela

**Comment by rafaparadela** [comment]
Sounds great to me @dmarticus go ahead. Thanks

**Comment by dmarticus** [comment]
I'm gonna keep this open until I can merge all the PRs related to it.

**Comment by dmarticus** [comment]
Everything got merged in so I'm closing this issue out.
