### ISSUE TITLE
Can I use a nightly build until the next release?

### ISSUE THREAD

**Issue by axtsnee** [higherkindness/sbt-mu-srcgen#429]
Hello. Thank you for creating and maintaining this great package.

My project requires `FEATURE_PROTO3_OPTIONAL` which I see is supported in the main branch but not the most recent release. Were you planning on creating a new release anytime soon? That would be ideal, but if not, do you publish nightly builds somewhere accessible?

**Comment by fedefernandez** [comment]
Hi

Yes, I'm planning to release a new version this week, but in the meantime, the latest version is `0.31.0+8-171772a6-SNAPSHOT`, and it should be available in [Sonatype snapshots repository](https://s01.oss.sonatype.org/content/repositories/snapshots/).

**Comment by axtsnee** [comment]
Thanks!
